-- MySQL Script generated by MySQL Workbench
-- Wed Feb 13 17:03:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `City_UNIQUE` (`City` ASC),
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Places` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CityId` INT UNSIGNED NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  CONSTRAINT `City`
    FOREIGN KEY (`Id`)
    REFERENCES `mydb`.`Cities` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `PlaceId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `Place_idx` (`PlaceId` ASC) ,
  CONSTRAINT `CustomerPlace`
    FOREIGN KEY (`PlaceId`)
    REFERENCES `mydb`.`Places` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlacesUpdates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlacesUpdates` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UpdateDate` DATETIME(6) NOT NULL,
  `CustomerId` INT UNSIGNED NOT NULL,
  `PlaceId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Customer_idx` (`CustomerId` ASC),
  INDEX `Place_idx` (`PlaceId` ASC),
  CONSTRAINT `Customer`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UpdatePlace`
    FOREIGN KEY (`PlaceId`)
    REFERENCES `mydb`.`Places` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;